const TREATMENTS = [
  {
    id: "norepinephrine",
    name: "NOR-EPINEPHRINE INFUSION",
    stockAmount: 12,
    stockUnit: "mg",
    dilutionMl: 50,
    timeFactor: 60,
    unitNote: "Order usually in mcg/kg/min",
    preparation: "38 ml D5W/NS + 12 ml Nor-epinephrine = 50 ml",
    mode: "weightedWithStock",
  },
  {
    id: "dopamine",
    name: "DOPAMINE INFUSION",
    stockAmount: 200,
    stockUnit: "mg",
    dilutionMl: 50,
    timeFactor: 60,
    unitNote: "Order usually in mcg/kg/min",
    preparation: "45 ml D5W/NS + 5 ml Dopamine = 50 ml",
    mode: "weightedWithStock",
  },
  {
    id: "rocuronium",
    name: "ROCURONIUM INFUSION",
    stockAmount: 50,
    stockUnit: "mg",
    dilutionMl: 50,
    timeFactor: 60,
    unitNote: "Order usually in mcg/kg/min",
    preparation: "45 ml D5W/NS + 5 ml Rocuronium = 50 ml",
    mode: "weightedWithStock",
  },
  {
    id: "ketamine",
    name: "KETAMINE INFUSION",
    stockAmount: 200,
    stockUnit: "mg",
    dilutionMl: 50,
    timeFactor: 60,
    unitNote: "Order usually in mg/kg/min",
    preparation: "30 ml D5W/NS + 20 ml Ketamine = 50 ml",
    mode: "weightedWithStock",
  },
  {
    id: "dobutamine",
    name: "DOBUTAMINE INFUSION",
    stockAmount: 250,
    stockUnit: "mg",
    dilutionMl: 50,
    timeFactor: 60,
    unitNote: "Order usually in mcg/kg/min",
    preparation: "45 ml D5W/NS + 5 ml Dobutamine = 50 ml",
    mode: "weightedWithStock",
  },
  {
    id: "lasix",
    name: "LASIX INFUSION",
    stockAmount: 100,
    stockUnit: "mg",
    dilutionMl: 30,
    timeFactor: 1,
    unitNote: "Order usually in mg/kg/hr",
    preparation: "20 ml D5W/NS + 10 ml Lasix = 30 ml",
    mode: "weightedWithStock",
  },
  {
    id: "heparin",
    name: "HEPARIN INFUSION",
    concentrationAmount: 25000,
    concentrationUnit: "IU",
    quantityMl: 50,
    unitNote: "Use direct desired dose in units",
    preparation: "45 ml NS + 25,000 IU Heparin = 50 ml",
    mode: "quantityByConcentration",
  },
  {
    id: "ammonul",
    name: "AMMONUL PREPARATION",
    stockAmount: 5000,
    stockUnit: "mg",
    quantityMl: 50,
    unitNote: "Enter direct dose in mg",
    preparation: "Reference ratio: 5,000 mg in 50 ml",
    mode: "quantityByStock",
  },
  {
    id: "fentanyl",
    name: "FENTANYL INFUSION",
    stockAmount: 500,
    stockUnit: "mcg",
    dilutionMl: 30,
    timeFactor: 1,
    unitNote: "Order usually in mcg/kg/hr",
    preparation: "20 ml D5W/NS + 10 ml Fentanyl = 30 ml",
    mode: "weightedWithStock",
  },
  {
    id: "midazolam",
    name: "MIDAZOLAM INFUSION",
    stockAmount: 45,
    stockUnit: "mg",
    dilutionMl: 50,
    timeFactor: 60,
    unitNote: "Order usually in mcg/kg/min",
    preparation: "41 ml D5W/NS + 9 ml Midazolam = 50 ml",
    mode: "weightedWithStock",
  },
  {
    id: "sandostatin",
    name: "SANDOSTATIN INJECTION",
    dilutionMl: 50,
    timeFactor: 1,
    unitNote: "Order usually in mcg/kg/hr",
    preparation: "0.1 mg/ml, calculated without stock divisor",
    mode: "weightedNoStock",
  },
  {
    id: "epinephrine",
    name: "EPINEPHRINE INFUSION",
    stockAmount: 1,
    stockUnit: "mg",
    dilutionMl: 50,
    timeFactor: 60,
    unitNote: "Order usually in mcg/kg/min",
    preparation: "40 ml D5W/NS + 10 ml Epinephrine = 50 ml",
    mode: "weightedWithStock",
  },
  {
    id: "diazepam",
    name: "DIAZEPAM INJECTION",
    conversionFactor: 0.2,
    unitNote: "Do not dilute. 1 mg = 0.2 ml",
    preparation: "Direct conversion only",
    mode: "mgToMlConversion",
  },
];
